markdown: rdiscount
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]

name: Marius Andreiana
url: https://mariusa.github.io
description: I solve business problems by using technology

